persistence:
  enabled: true
  url: "mongodb://localhost:27017"
  type: "mongodb"
  db: "nexus"
http:
  addr: 127.0.0.1:7777
  jwt:
    secret: "123456"
    expire: "72h"
email:
  enabled: false
  host: "smtp.qq.com"
  port: 587
  username: "2318266924@qq.com"
  password: "ohzbejbiiahtebbg"