persistence:
  enabled: true
#  url: "mongodb://mongodb:27017"
  url: mongodb://root:root@mongodb:27017/nexus
  type: "mongodb"
  db: "nexus"
http:
  addr: :7777
  server: "<server-ip>:7777"
  jwt:
    secret: ""
    expire: "72h"
email:
  enable: false
  host: ""
  port:
  username: ""
  password: ""